### ISSUE TITLE
Failed to find an action that matches the metadata specified by the activity with id '0cbda03e-4dc7-406f-b9ae-00bcc615c36a'

### ISSUE THREAD

**Issue by whuanle** [serverlessworkflow/specification#713]
**example:**
[https://github.com/serverlessworkflow/specification/blob/main/examples/README.md#Greeting-Example](https://github.com/serverlessworkflow/specification/blob/main/examples/README.md#Greeting-Example)

**swagger:**
![image](https://user-images.githubusercontent.com/2189761/202632480-d975c77e-70a7-4f38-bbcb-d65ca212c489.png)
![image](https://user-images.githubusercontent.com/2189761/202632593-2400221e-d3a9-4a94-96d6-895e865c8169.png)

**wokflow:**
![image](https://user-images.githubusercontent.com/2189761/202632648-9a3894d8-8e3c-466b-a527-46837e082748.png)

```json
{
  "id": "greeting",
  "name": "Greeting Workflow",
  "description": "Greet Someone",
  "version": "1.0.11",
  "specVersion": "0.8",
  "functions": [
    {
      "name": "greetingFunction",
      "operation": "http://192.168.70.122:18080/swagger/v1/swagger.json#greeting",
      "type": "rest"
    }
  ],
  "start": "Greet",
  "states": [
    {
      "name": "Greet",
      "type": "operation",
      "actions": [
        {
          "actionDataFilter": {
            "results": "${ {greeting: .greeting} }"
          },
          "functionRef": {
            "refName": "greetingFunction",
            "arguments": {
              "name": "${ .person.name }"
            }
          }
        }
      ],
      "end": true
    }
  ]
}
```

**arguments:**
![image](https://user-images.githubusercontent.com/2189761/202632823-8e64d5d3-be02-412a-bdb7-94c54a5322a6.png)

**result:**
![image](https://user-images.githubusercontent.com/2189761/202632864-2571a3fc-7179-4e83-9b84-5670c5fdf05c.png)
![image](https://user-images.githubusercontent.com/2189761/202632901-8b88a284-c95d-42a0-9937-2b465972600b.png)

```json
{
  "code": "NullReference",
  "message": "Failed to find an action that matches the metadata specified by the activity with id 'a0518b8b-d25c-4dd5-acbd-84a74400b7e5'"
}
```

**log:**

```bash
[06:06:46] info: Synapse.Worker.Services.WorkflowRuntimeContext[0]
      Initializing the runtime context for workflow instance with id 'greeting-zlcsw8deuk2ya7hnvyora'...
[06:06:46] info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
[06:06:46] info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
[06:06:46] info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
[06:06:46] info: Synapse.Worker.Services.WorkflowRuntimeContext[0]
      Retrieving definition of workflow with id 'greeting:1.0.12'...
[06:06:47] info: Synapse.Worker.Services.WorkflowRuntimeContext[0]
      Runtime context initialized
[06:06:47] info: Synapse.Worker.Services.WorkflowRuntime[0]
      Starting the workflow's execution...
[06:06:47] info: Synapse.Worker.Services.Processors.OperationStateProcessor[0]
      Initializing activity 'a484a22e-b0e5-49c6-9837-ac3e64c2d49d' (type: 'State')...
[06:06:47] fail: Synapse.Worker.Services.WorkflowActivityProcessorFactory[0]
      An error occured while creating a new processor for the activity with id 'a0518b8b-d25c-4dd5-acbd-84a74400b7e5': System.NullReferenceException: Failed to find an action that matches the metadata specified by the activity with id 'a0518b8b-d25c-4dd5-acbd-84a74400b7e5'
         at Synapse.Worker.Services.WorkflowActivityProcessorFactory.CreateActionActivityProcessor(StateDefinition state, V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessorFactory.cs:line 125
         at Synapse.Worker.Services.WorkflowActivityProcessorFactory.Create(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessorFactory.cs:line 72
[06:06:47] warn: Synapse.Worker.Services.Processors.OperationStateProcessor[0]
      An error occured while executing the activity 'a484a22e-b0e5-49c6-9837-ac3e64c2d49d' (type: 'State')/r/nDetails:/r/nSystem.NullReferenceException: Failed to find an action that matches the metadata specified by the activity with id 'a0518b8b-d25c-4dd5-acbd-84a74400b7e5'
         at Synapse.Worker.Services.WorkflowActivityProcessorFactory.CreateActionActivityProcessor(StateDefinition state, V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessorFactory.cs:line 125
         at Synapse.Worker.Services.WorkflowActivityProcessorFactory.Create(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessorFactory.cs:line 72
         at Synapse.Worker.Services.WorkflowActivityProcessorFactory.Synapse.Worker.Services.IWorkflowActivityProcessorFactory.Create(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessorFactory.cs:line 320
         at Synapse.Worker.Services.WorkflowActivityProcessor.CreateProcessorFor(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessor.cs:line 196
         at Synapse.Worker.Services.Processors.OperationStateProcessor.CreateProcessorFor(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/Processors/OperationStateProcessor.cs:line 50
         at Synapse.Worker.Services.Processors.OperationStateProcessor.StartAsync() in /src/src/apps/Synapse.Worker/Services/Processors/OperationStateProcessor.cs:line 107
         at Synapse.Worker.Services.Processors.OperationStateProcessor.InitializeAsync(CancellationToken cancellationToken) in /src/src/apps/Synapse.Worker/Services/Processors/OperationStateProcessor.cs:line 64
         at Synapse.Worker.Services.WorkflowActivityProcessor.<>c__DisplayClass30_0.<<Synapse-Worker-Services-IWorkflowActivityProcessor-ProcessAsync>b__0>d.MoveNext() in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessor.cs:line 105
[06:06:47] warn: Synapse.Worker.Services.WorkflowRuntime[0]
      An error occured while executing the workflow instance: System.NullReferenceException: Failed to find an action that matches the metadata specified by the activity with id 'a0518b8b-d25c-4dd5-acbd-84a74400b7e5'
         at Synapse.Worker.Services.WorkflowActivityProcessorFactory.CreateActionActivityProcessor(StateDefinition state, V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessorFactory.cs:line 125
         at Synapse.Worker.Services.WorkflowActivityProcessorFactory.Create(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessorFactory.cs:line 72
         at Synapse.Worker.Services.WorkflowActivityProcessorFactory.Synapse.Worker.Services.IWorkflowActivityProcessorFactory.Create(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessorFactory.cs:line 320
         at Synapse.Worker.Services.WorkflowActivityProcessor.CreateProcessorFor(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessor.cs:line 196
         at Synapse.Worker.Services.Processors.OperationStateProcessor.CreateProcessorFor(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/Processors/OperationStateProcessor.cs:line 50
         at Synapse.Worker.Services.Processors.OperationStateProcessor.StartAsync() in /src/src/apps/Synapse.Worker/Services/Processors/OperationStateProcessor.cs:line 107
         at Synapse.Worker.Services.Processors.OperationStateProcessor.InitializeAsync(CancellationToken cancellationToken) in /src/src/apps/Synapse.Worker/Services/Processors/OperationStateProcessor.cs:line 64
         at Synapse.Worker.Services.WorkflowActivityProcessor.<>c__DisplayClass30_0.<<Synapse-Worker-Services-IWorkflowActivityProcessor-ProcessAsync>b__0>d.MoveNext() in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessor.cs:line 105
[06:06:47] info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...

```

**Comment by cdavernas** [comment]
@whuanle The issue is not related to the OpenAPI itself, but is due to the worker not able to find the action within the definition. Now, this could be related to a bad PROTOBUF serialization. I'll investigate.

**Comment by whuanle** [comment]
Maybe it has something to do with these properties：
![image](https://user-images.githubusercontent.com/2189761/202649390-85ef3384-3dc1-42fe-9c78-eb55dcaef172.png)

I am modifying the sample

**Comment by whuanle** [comment]
Do not work...
```csharp
using Microsoft.AspNetCore.Mvc;
using System.Net;

namespace Example1.Controllers;

/// <summary>
///  Greeting Workflow
/// </summary>
[ApiController]
[Route("[controller]")]
public class GreetingWorkflowController : ControllerBase
{
    private readonly ILogger<GreetingWorkflowController> _logger;

    public GreetingWorkflowController(ILogger<GreetingWorkflowController> logger)
    {
        _logger = logger;
    }

    /// <summary>
    /// greeting
    /// </summary>
    /// <param name="input"></param>
    /// <returns></returns>
    [ProducesResponseType(typeof(GreetingWorkOutput), (int)HttpStatusCode.OK)]
    [HttpPost(Name = "greeting")]
    public GreetingWorkOutput GetGreeting(GreetingWorkInput input)
    {
        return new GreetingWorkOutput { Greeting = "Welcome to Serverless Workflow, " + input.Person.Name };
    }

    public class GreetingWorkInput
    {
        public PersonInput Person { get; set; }

        public class PersonInput
        {
            public string Name { get; set; }
        }
    }

    public class GreetingWorkOutput
    {
        public string Greeting { get; set; }
    }
}

```

**Comment by whuanle** [comment]
![20221118-160606](https://user-images.githubusercontent.com/2189761/202652198-963e890f-febd-4603-8959-b85f5dd0530c.gif)

**Comment by whuanle** [comment]
```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "Example1",
    "version": "1.0"
  },
  "paths": {
    "/GreetingWorkflow": {
      "post": {
        "tags": [
          "GreetingWorkflow"
        ],
        "operationId": "greeting",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/GreetingWorkInput"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/GreetingWorkInput"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/GreetingWorkInput"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/GreetingWorkOutput"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GreetingWorkOutput"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/GreetingWorkOutput"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "GreetingWorkInput": {
        "type": "object",
        "properties": {
          "person": {
            "$ref": "#/components/schemas/PersonInput"
          }
        },
        "additionalProperties": false
      },
      "GreetingWorkOutput": {
        "type": "object",
        "properties": {
          "greeting": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "PersonInput": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      }
    }
  }
}
```

**Comment by cdavernas** [comment]
@whuanle So could you make it work?

**Comment by whuanle** [comment]
@cdavernas no...

**Comment by whuanle** [comment]
@cdavernas 
![image](https://user-images.githubusercontent.com/2189761/202842096-87392b68-0939-4054-96b2-1457ebb7d1e3.png)
![image](https://user-images.githubusercontent.com/2189761/202842106-bef15a23-827e-4e6c-905a-528e513767b5.png)
